---
production:
  - name: "hub.njrusmc.net"
    role: "hub"  # unused; retained for consistency
  - name: "site2.njrusmc.net"
    role: "spoke"  # unused; retained for consistency
  - name: "site3.njrusmc.net"
    role: "spoke"  # unused; retained for consistency
...
